"""Mutation operations for `offboard execute`.

This module is the ONLY place ai-offboard performs writes against Graph.
Every operation is:
1. Generated by the dry-run planner (plan/planner.py)
2. Reviewed by the user via `offboard execute`'s approval gate
3. Logged to the local store (executions table) BEFORE and AFTER the call

All methods are idempotent-safe: they look up the subject first and no-op
if it's already in the desired state.
"""
from __future__ import annotations

from typing import ClassVar

import requests

from .auth import GRAPH_ROOT
from .connectors.entra import EntraConnector
from .connectors.mock import MockConnector


class Executor:
    """Applies a StepSpec list to the tenant via the authenticated connector.

    When given a non-Entra connector (e.g. MockConnector in --mock mode),
    operations are SIMULATED: they return 'ok' without touching Graph, so the
    approval gate, audit logging, and sequencing can be demonstrated end to
    end without credentials.
    """

    def __init__(self, connector: EntraConnector | MockConnector) -> None:
        self._connector = connector
        self._simulated = not hasattr(connector, "_auth")

    # -- helpers ----------------------------------------------------------

    def _auth_headers(self) -> dict[str, str]:
        if self._simulated:
            return {}
        from typing import cast

        entra = cast(EntraConnector, self._connector)
        return {"Authorization": f"Bearer {entra._auth()}"}

    def _find_user(self, upn: str) -> str | None:
        """Find a user by UPN or email; returns their Graph object id."""
        url = f"{GRAPH_ROOT}/users/{upn}"
        resp = requests.get(url, headers=self._auth_headers(), timeout=30)
        if resp.status_code == 200:
            return resp.json().get("id")
        return None

    # -- operations -------------------------------------------------------

    def block_signin(self, target: str) -> dict:
        """Disable sign-in for a user UPN. Non-destructive; reversible."""
        if self._simulated:
            return {"action": "block_signin", "target": target, "status": "ok", "simulated": True}
        user_id = self._find_user(target)
        if user_id is None:
            return {"action": "block_signin", "target": target, "status": "not_found"}
        url = f"{GRAPH_ROOT}/users/{user_id}"
        resp = requests.patch(url, headers=self._auth_headers(), json={"accountEnabled": False}, timeout=30)
        if resp.status_code in (200, 204):
            return {"action": "block_signin", "target": target, "status": "ok"}
        return {"action": "block_signin", "target": target, "status": "failed", "detail": resp.text}

    def revoke_tokens(self, target: str) -> dict:
        """Revoke a user's refresh tokens / SSO sessions."""
        if self._simulated:
            return {"action": "revoke_tokens", "target": target, "status": "ok", "simulated": True}
        user_id = self._find_user(target)
        if user_id is None:
            return {"action": "revoke_tokens", "target": target, "status": "not_found"}
        url = f"{GRAPH_ROOT}/users/{user_id}/revokeSignInSessions"
        resp = requests.post(url, headers=self._auth_headers(), timeout=30)
        if resp.status_code in (200, 204):
            return {"action": "revoke_tokens", "target": target, "status": "ok"}
        return {"action": "revoke_tokens", "target": target, "status": "failed", "detail": resp.text}

    def remove_assignment(self, target: str) -> dict:
        """Remove a service principal (enterprise app) — revokes its access.

        NOTE: targets are matched by app display name; exact SP id matching
        requires the snapshot's service principal ids, which the planner
        carries in the StepSpec only for v2. This best-effort path removes
        the first matching service principal by display name.
        """
        if self._simulated:
            return {"action": "remove_assignment", "target": target, "status": "ok", "simulated": True}
        url = f"{GRAPH_ROOT}/servicePrincipals?$filter=appDisplayName+eq+'{target}'"
        resp = requests.get(url, headers=self._auth_headers(), timeout=30)
        sps = resp.json().get("value", []) if resp.status_code == 200 else []
        if not sps:
            return {"action": "remove_assignment", "target": target, "status": "not_found"}
        sp_id = sps[0]["id"]
        del_url = f"{GRAPH_ROOT}/servicePrincipals/{sp_id}"
        del_resp = requests.delete(del_url, headers=self._auth_headers(), timeout=30)
        if del_resp.status_code in (200, 204):
            return {"action": "remove_assignment", "target": target, "status": "ok"}
        return {"action": "remove_assignment", "target": target, "status": "failed", "detail": del_resp.text}

    METHOD_MAP: ClassVar[dict[str, str]] = {
        "block_signin": "block_signin",
        "revoke_token": "revoke_tokens",
        "revoke_license": "remove_assignment",  # license revocation exposed as SP removal
        "remove_assignment": "remove_assignment",
    }

    def execute(self, action: str, target: str) -> dict:
        method_name = self.METHOD_MAP.get(action)
        if method_name is None:
            return {"action": action, "target": target, "status": "unknown_action"}
        return getattr(self, method_name)(target)